pipeline {
    agent any

    tools {
        maven 'mvn'
        jdk 'jdk17'
    }

    stages {
        stage('git checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Nandhu-13/prasadjava.git'
            }
        }

        stage('mvn compile') {
            steps {
                sh 'mvn clean compile -DskipTests'
            }
        }

        stage('mvn test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('mvn package') {
            steps {
                sh 'mvn package -DskipTests'
            }
        }
    }
}
